<a href="https://colab.research.google.com/github/kamrulhuda/TensorflowTutorial/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2

In [2]:
import os
os.environ ['TF_CPP_MIN_LOG_LEVEL']= '2'

In [3]:
import tensorflow as tf #fundamental building blocks of deep learing    

In [4]:
#Initializing of tensors
x= tf.constant(4.0, shape=(1,1), dtype=tf.float32)
print(x)
x= tf.constant([[1,2,3],[4,5,6]])
print(x)
x= tf.ones((3,3))
print(x)
x= tf.zeros((2,3))
print(x)
x= tf.eye(3)
print(x)
x= tf.random.normal((3,3), mean=0,stddev=1)
print(x)
x= tf.random.uniform((1,3), minval=0, maxval=1)
print(x)
x= tf.range(9)
print(x)
x= tf.range(start=1, limit=19, delta=2)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.01666949  0.3457884  -0.2081575 ]
 [ 0.5932417   1.3666451  -0.31936002]
 [ 1.3844962   0.2871396   2.112932  ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.87738323 0.5199487  0.9320886 ]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([ 1  3  5  7  9 11 13 15 17], shape=(9,), dtype=int32)


In [5]:
#Converting the data type
x= tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17.], shape=(9,), dtype=float64)


In [6]:
#mathematical Operations of Tensors
x= tf.constant([12,2,2])
y= tf.constant([2,3,4])
z=tf.add(x,y)
z1= tf.subtract(x,y)
z2=tf.divide(x,y)
z3= tf.multiply(x,y)
z4= tf.tensordot(x,y, axes=1) # Element wise multiplication and then subtraction
print(z4)
z5= x**5
print(z5)
 #Matris Multiplication
x= tf.random.normal((2,3))
y= tf.random.normal((3,4))
z6= tf.matmul(x,y)
print(z6)

tf.Tensor(38, shape=(), dtype=int32)
tf.Tensor([248832     32     32], shape=(3,), dtype=int32)
tf.Tensor(
[[-2.7157617  -1.0510737   0.60156274  2.8560214 ]
 [ 0.63561857  1.2472357  -3.5182457  -3.0133095 ]], shape=(2, 4), dtype=float32)


In [8]:
#Indexing
x= tf.constant([0,1,1,12,3,4,2])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])


tf.Tensor([ 0  1  1 12  3  4  2], shape=(7,), dtype=int32)
tf.Tensor([ 1  1 12  3  4  2], shape=(6,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([ 2  4  3 12  1  1  0], shape=(7,), dtype=int32)


In [13]:
#Reshaping
x=tf.range(9)
print(x)
x= tf.reshape(x, (3,3))
print(x)
x= tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [ ]:
e